# Cấu hình tải file RPM
settings:
  download_dir: "rpm_files"

repositories:
- title: "OpenSUSE Leap 15.0 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/15.0/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.0 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/15.0/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.1 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/15.1/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.1 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/15.1/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.2 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/15.2/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.2 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/15.2/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.3 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/15.3/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.3 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/15.3/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.4 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/15.4/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.4 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/15.4/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.5 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/15.5/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.5 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/15.5/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.6 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/15.6/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 15.6 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/15.6/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 16.0 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/16.0/repo/oss/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 16.0 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/16.0/repo/oss/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 42.3 - x86_64"
  start_url: "https://download.opensuse.org/distribution/leap/42.3/repo/oss/suse/x86_64/"
  file_patterns: ["kernel", "devel", "x86_64", "default"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse

- title: "OpenSUSE Leap 42.3 - noarch"
  start_url: "https://download.opensuse.org/distribution/leap/42.3/repo/oss/suse/noarch/"
  file_patterns: ["kernel", "devel", "noarch"]
  file_not_patterns: ["patterns"]
  download_folder: package-suse
  output_folder: output-suse